/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'First Leap',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.1,
      timeLimitSeconds: null,
      targetScore: 100,
      obstacleCount: 2,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'sunny_day',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Rising Steps',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: null,
      targetScore: 150,
      obstacleCount: 3,
      obstacleSpeed: 0,
      collectibleCount: 15,
      collectibleValue: 10,
      backgroundTheme: 'morning_meadows',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Leap of Faith',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: null,
      targetScore: 200,
      obstacleCount: 5,
      obstacleSpeed: 0,
      collectibleCount: 20,
      collectibleValue: 10,
      backgroundTheme: 'cloudy_skies',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Moving On',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.4,
      timeLimitSeconds: null,
      targetScore: 250,
      obstacleCount: 2,
      obstacleSpeed: 1,
      collectibleCount: 25,
      collectibleValue: 10,
      backgroundTheme: 'twilight_town',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Twist and Turn',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: null,
      targetScore: 300,
      obstacleCount: 5,
      obstacleSpeed: 2,
      collectibleCount: 30,
      collectibleValue: 10,
      backgroundTheme: 'night_navigator',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Skyward Bound',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: null,
      targetScore: 350,
      obstacleCount: 7,
      obstacleSpeed: 3,
      collectibleCount: 35,
      collectibleValue: 10,
      backgroundTheme: 'starry_night',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'The Gauntlet',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: null,
      targetScore: 400,
      obstacleCount: 10,
      obstacleSpeed: 4,
      collectibleCount: 40,
      collectibleValue: 10,
      backgroundTheme: 'lava_lands',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Perilous Peaks',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: null,
      targetScore: 450,
      obstacleCount: 12,
      obstacleSpeed: 5,
      collectibleCount: 45,
      collectibleValue: 10,
      backgroundTheme: 'snowy_slopes',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Echoes of the Void',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: null,
      targetScore: 500,
      obstacleCount: 15,
      obstacleSpeed: 6,
      collectibleCount: 50,
      collectibleValue: 10,
      backgroundTheme: 'void_vista',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Final Frontier',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 1.0,
      timeLimitSeconds: null,
      targetScore: 550,
      obstacleCount: 20,
      obstacleSpeed: 7,
      collectibleCount: 55,
      collectibleValue: 10,
      backgroundTheme: 'cosmic_canyon',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
